# Generated by Django 3.1.7 on 2024-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_auto_20240708_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='types',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Express', 'Express'), ('AC', 'AC')], max_length=20),
        ),
    ]
